---
- hosts: all
  become: true
  tasks:
  
  - name: install apache2,MySQL,php 
    apt:
      name:
      - apache2
      - mysql-server
      - libapache2-mod-php
      state: latest
      update_cache: yes
  - name: starting mysql services
    tags: staring services
    action: service name=mysql state=started

  - name: restart apache2
    service:
      name: apache2
      state: restarted
  
  - name: default site
    tags: apache,apache2,httpd
    copy:
      src: sites/default_site.html  # give your own site
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0664



