---
- hosts: all
  become: true
  tasks:
  
  - name: install apache2 &  php packages for Debian  and Ubuntu
    apt:
      name:
      - apache2
      - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution  in ["Ubuntu", "Debian"]

  - name: install httpd & php packages for CentOS
    dnf: 
      name: 
      - httpd
      - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
    
  - name: default site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html  # give your own site
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0664
