- name: Install MySQL for production ready server
  hosts: all
  become: True
  become_user: root
  tasks:
    - name: installig MySQL
      apt:
        package:
            - mysql-server
            - mysql-client
            - python-mysqldb
        state: present
        force: yes
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Ubuntu"

    - name: Save root password in .my.cnf
      template:
       src: root_cnf.j2
       dest: /root/.my.cnf
       owner: root
       mode: '0600'

    - name: Set password for root user
      mysql_user:
         name: root
         password: root
         priv: '*.*:ALL,GRANT'
         host: 'localhost'
         login_unix_socket: /var/run/mysqld/mysqld.sock
         state: present