---
- name: installing asteriks prerequisites
  hosts: all
  become: true
  tasks:
  
  - name: asteriks dependencies
    apt:
      name:
      - git 
      - curl 
      - wget 
      - libnewt-dev
      - libssl-dev
      - libncurses5-dev 
      - subversion 
      - libsqlite3-dev
      - build-essential
      - libjansson-dev
      - libxml2-dev
      - uuid-dev
      - libedit

  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest
