- name: Install MySQL for production ready server
  hosts: all
  become: True
  become_user: root
  tasks:
    - name: installig MySQL
      apt:
        name:
        - mysql-server
        - mysql-client
        - python-mysqldb
        state: present
        force: yes
        update_cache: yes
    
    - name: Make sure pymysql is present
      apt:
        name:
          - python3-pip
          - python3-dev
          - python3-mysqldb
        state: present
        force: yes
        update_cache: yes
    - name: starting mysql service
      service:
         name: mysql
         state: started
    - name: Save root password in .my.cnf
      template:
       src: ./root_cnf.j2
       dest: /root
       owner: root
       mode: '0600'