---
- name: installing nginx & php
  hosts: all
  become: true
  tasks:
  
  - name: install nginx
    apt:
      name:
      - nginx
      state: latest
      update_cache: yes
  - name: install  php packages 
    apt:
      name:
      - libapache2-mod-php
      - php-cli
      - php-gd
      - php-fpm
      - php-common
      - php-mbstring
      - php-xmlrpc
      - php-xml
      - php-mysql
      - php-zip
      - php-curl
      state: latest
      update_cache: yes
  - name: enabling the nginx service
    ansible.builtin.systemd:
      name: nginx
      enabled: yes
      masked: no
      
  - name: reloading the nginx service
    ansible.builtin.systemd:
       name: nginx
       state: reloaded
  
  

