---
- hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Deploy SSH Key
      authorized_key:
          user: root
          state: present
          key:  "{{ lookup('file', '/root/.ssh/authorized_keys') }}"

    - name: Disable Password Authentication
      lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes
      notify:
        - restart ssh

  handlers:
    - name: restart ssh
      service:
        name=sshd
        state=restarted
